name: build-linux-x64-lite

on:
  push:
    branches: [ "4.x" ]
  pull_request:
    branches: [ "4.x" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare for build the opencv-python image
      run: |
          sudo apt-get update
          sudo apt-get -y install git python3 python3-pip cmake gcc g++ ninja-build
          /usr/bin/python3 -m pip install --upgrade pip 
          /usr/bin/python3 -m pip install scikit-build==0.12.0 numpy
          export CMAKE_ARGS='-DCMAKE_VERBOSE_MAKEFILE=ON'
          export VERBOSE=1
    - name: build
      run: |
          /usr/bin/python3 ./setup.py bdist_wheel --build-type=Release 
